--sander
ALTER TABLE reservations
    ADD COLUMN start_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE reservations
    ADD COLUMN end_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
